### PR TITLE
made code look good

### PR DESCRIPTION
**Pull request by Chronophylos**
fixed a lot of formatting errors
increased framerate from 200 to 1024 because being lower is not a problem
moved size into settings like the documetation says. this fixed a display issue on linux with a tiling wm
added some comments

### CODE REVIEW

**Comment by hanss314** [comment]
Wait, but I already made a PR with changes made to neuralNetworkLanguageDetection.pde. How will this work out? Should I manually copy my changes to your files or is there a better way to do this?

**Comment by hanss314** [comment]
Also, the documentation that I read said size() should be the first method in setup () not on settings().

**Comment by ZweiSpeedruns** [comment]
GitHub automerges 99.99% of the time

**Comment by phase** [comment]
There's no way there won't be merge conflicts with this.

**Comment by ZweiSpeedruns** [comment]
I've never seen a merge conflict, but taking another look you're probably right. If they both get merged, one will have a merge conflict which must be resolved on another branch before it's merged.

**Comment by hanss314** [comment]
I've kind of resolved it. I copied my code into his code and commited it to my branch. However, I moved size() back into setup(). I can move it back to settings() if it's mandatory for linux. There shouldn't be any problems though, since the vm runs the code.

**Comment by Chronophylos** [comment]
now everything is tested and working

**Comment by hanss314** [comment]
size() should be the first method in setup().

**Comment by hanss314** [comment]
Also could you please fix the one line if statements. They are ugly and harder to read.

**Comment by Chronophylos** [comment]
But oneliner are cool

**Comment by hanss314** [comment]
But the convention is to have multiliners. If you didn't change anything except for the brackets and size() then I have the same copy as you.

**Comment by Chronophylos** [comment]
@zekeroonie found out size(1100, 600) is the size we want. I did that as well

**Comment by hanss314** [comment]
The size depends on monitor size. I'll see if there's a way to get the best size when I have time.

**Comment by hanss314** [comment]
Pretty sure I fixed window scaling for good. I have the changes on my branch if you want to check them out. Still have to do some more testing.

**Comment by ZweiSpeedruns** [comment]
>made code look good
>added one-line if statements

what

**Comment by Chronophylos** [comment]
What

**Comment by hanss314** [comment]
He means that one line statements don't look good

**Comment by Chronophylos** [comment]
Ahh. I just woke up. I think oneliners look good but i can't say anything against a conventions.

**Comment by hanss314** [comment]
Well i'm about to go to sleep Cuz timezones

**Comment by phase** [comment]
I use `if (state) action()` a lot, but `if (state) { action() }` is begging to be indented.

**Comment by dangeredwolf** [comment]
My fork is fully compatible with Processing 3 and presumably Processing 2: Yes, scaling included.

https://github.com/dangeredwolf/neuralNetworkLanguageDetection

In a nutshell:

`
    size(1000, 580); //fallback at 0.5 scale
    surface.setResizable(true);
    surface.setSize((int)(WINDOW_SCALE_SIZE * 2000),(int)(WINDOW_SCALE_SIZE * 1160));
    surface.setResizable(false);
`

_Note: If you have this inside an if statement, like I had, you'll need to declare the fallback **beforehand**_

**Comment by hanss314** [comment]
It won't work in 2. surface is new to 3.

**Pull request closed without merging**
